name: vurelo
description: "Vurelo app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: null
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  intl: ^0.18.1
  overlay_support: ^2.1.0
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
